### ISSUE TITLE
Can't step after loading scenario

### ISSUE THREAD

**Issue by FelixDuxNATS** [project-bluebird/bluebird#89]
This was observed on the develop branch running with --simtype machcoll.

It appears that `pydodo.scenario.load_scenario` is now redundant, as it seeks to use an endpoint which is not in the default configuration file. `pydodo.scenario.create_scenario` should be sufficient by itself as it invokes the `/scenario` endpoint, which demonstrably loads a scenario into the simulator. However, subsequent calls to the `/step` endpoint fail, reporting "No scenario set" (`bluebird/sim_proxy/proxy_simulator_controls.py`, line 171).

**Comment by FelixDuxNATS** [comment]
Further investigation reveals that this was occurring because my pseudo-agent was sending a `/rest` endpoint request after loading the scenario and this causes the `._scenario' member variable to be reset to `None`

**Comment by radka-j** [comment]
Clearing all aircraft data (i.e., a scenario) is the correct behaviour when calling the RESET endpoint so I am closing this issue.
