### ISSUE TITLE
Dockerfile assumes only NATSPyPI packages in requirements-nats.txt

### ISSUE THREAD

**Issue by FelixDuxNATS** [project-bluebird/bluebird#90]
As currently written, the Dockerfile uses the NatsPyPI server as the sole index-url when pip installing from reuqirements-nats.txt. But the latter file also references pika, so this will fail. This is easily rectified. I would propose a fix in a PR, but don't currently have sufficient permissions.

**Comment by radka-j** [comment]
This seems to have been resolved in #91
